name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install dependencies
      run: npm ci --no-audit --prefer-offline --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.LA_ACTIONS_TOKEN }}

    - name: Run tests
      run: npm test
