name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc
        npm ci --no-audit --prefer-offline --ignore-scripts
        rm .npmrc

    - name: Run tests
      run: npm test
